CREATE TABLE REGISTRO (  
    documento INTEGER PRIMARY KEY,  
    nombre TEXT,  
    correo TEXT,  
    password TEXT 
);  
 
CREATE TABLE PLAYER (  
    documento INTEGER,  
    equipo TEXT,  
    grado TEXT,  
    FOREIGN KEY (documento) REFERENCES REGISTRO(documento)  
);  
  
CREATE TABLE NO_PLAYER (  
    documento INTEGER,  
    grado TEXT,  
    FOREIGN KEY (documento) REFERENCES REGISTRO(documento)  
);  

CREATE TABLE USUARIOS (  
    id_documento INTEGER PRIMARY KEY,  
    documento INTEGER,  
    FOREIGN KEY (documento) REFERENCES REGISTRO(documento) 
);  
